### ISSUE TITLE
Extraction failure - too many open files

### ISSUE THREAD

**Issue by tjdurden** [surevine/gateway-management#78]
Apologies for the light detail; not quite sure what's caused this.
Spotted on .11 (test env) in /var/log/wildfly/console.log

15:53:36,613 INFO  [com.surevine.community.gateway.api.GatewayAPI] (default task-4) Extracting metadata to: /tmp/.export-quarantine/8feb043d-5d64-448f-a952-7414f43b0a3d/.extract_metadata
15:53:36,613 ERROR [io.undertow.request] (default task-4) UT005023: Exception handling request to /gateway/api/export: org.jboss.resteasy.spi.UnhandledException: java.io.IOException: Cannot run program "tar" (in directory "/tmp/.export-quarantine/8feb043d-5d64-448f-a952-7414f43b0a3d"): error=24, Too many open files
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76) [resteasy-jaxrs-3.0.6.Final.jar:]
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:212) [resteasy-jaxrs-3.0.6.Final.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:149) [resteasy-jaxrs-3.0.6.Final.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:372) [resteasy-jaxrs-3.0.6.Final.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:217) [resteasy-jaxrs-3.0.6.Final.jar:]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:224) [resteasy-jaxrs-3.0.6.Final.jar:]
	at org.jboss.resteasy.plugins.server.servlet.FilterDispatcher.doFilter(FilterDispatcher.java:62) [resteasy-jaxrs-3.0.6.Final.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:56) [undertow-servlet-1.0.0.Final.jar:1.0.0.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) [undertow-servlet-1.0.0.Final.jar:1.0.0.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85) [undertow-servlet-1.0.0.Final.jar:1.0.0.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) [undertow-servlet-1.0.0.Final.jar:1.0.0.Final]

**Comment by tjdurden** [comment]
Out of interest, is /tmp/.export-quarantine/ getting cleaned up on a regular interval?
